[package]
name = "flight-server-transform-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
path-slash = "0.2.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.145"
swc_core = { version = "9.0.3", features = ["ecma_plugin_transform", "testing", "ecma_parser", "ecma_quote"] }

