[package]
name = "flight-server-transform-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
path-slash = "0.2.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
swc_core = { version = "54.0.0", features = [
  "common",
  "ecma_ast",
  "ecma_visit",
  "ecma_parser",
  "ecma_quote",
  "ecma_plugin_transform",
  "testing",
] }
swc_atoms = "9.0.0"

