name: Reset repo and run prepare and run integration test

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  reset-prepare:
    name: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest] # ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
              turbo-${{ github.ref_name }}-

      - name: Install Pnpm
        run: npm install -g pnpm@7

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: reset
        run: rm -rf node_modules && rm -rf pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Prepare
        run: pnpm run prepare

      - name: Install Puppeteer
        run: cd ./tests/node_modules/puppeteer && npm run install && cd ../..

      - name: Test
        run: cd ./tests && pnpm run test

