name: Unit Test (jest - macOS)

concurrency:
  group: macos-test-${{ github.head_ref }}
  cancel-in-progress: true

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]

  merge_group:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ut-mac:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x]
        os: [macos-latest] # macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Install Pnpm
        run: corepack enable

      - name: Check skip CI
        run: |
          echo "RESULT=$(node ./scripts/skipCI.js)" >> "$GITHUB_OUTPUT"
          echo "${{steps.skip-ci.outputs.RESULT}}"
        id: skip-ci

      - name: Setup Node.js ${{ matrix.node-version }}
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm install --ignore-scripts

      - name: Test
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        run: pnpm run test:jest

      - name: Collect coverage
        if: ${{steps.skip-ci.outputs.RESULT != 'true'}}
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          override_branch: main
